        <div class="container">
            <hr>
            <a style="color: graytext"><i>2019 - Un proyecto FDI de la Universidad Tecnológica Metropolitana para el Cementerio General. <br>
                    Para servicio técnico, dudas y consultas, escriba un correo a <a href="http://mailto:proyectoarboreo@gmail.com"> proyectoarboreo@gmail.com</a></i></a>
            <br><br>
        </div>
    </body>
</html>
